platform :ios, '16.4'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
target 'globoplay' do
  use_frameworks!
  pod 'Alamofire', '5.9.1'
  pod 'SwiftLint', '0.55.1'
  pod 'SDWebImage'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
    end
  end
end

